{ inputs, ... }:
{
  flake.modules.nixos.security-agenix =
    { pkgs, ... }:
    {
      imports = [ inputs.agenix.nixosModules.default ];

      # Each host's dedicated age key, generated by install/install.sh
      # (which prints its public half for secrets.nix).
      age.identityPaths = [ "/var/lib/agenix/host.key" ];

      environment.systemPackages = [
        inputs.agenix.packages.${pkgs.stdenv.hostPlatform.system}.default
        pkgs.age # age-keygen, for the per-user key (README "Secrets")
      ];
    };
}
